# Generated by Django 2.2.13 on 2020-09-07 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('cpf', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(11)])),
                ('number_rg', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('finance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('informal_worker', models.BooleanField(default=True)),
                ('receives_payment', models.CharField(max_length=200, null=True)),
                ('card_companies', models.CharField(max_length=200, null=True)),
                ('token_myid', models.CharField(max_length=100, null=True)),
                ('token_company', models.CharField(max_length=100, null=True)),
                ('bank_used', models.CharField(max_length=50, null=True)),
                ('loan_reason', models.TextField(null=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('key', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_project',
            },
        ),
        migrations.CreateModel(
            name='CreditAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_serasa', models.CharField(max_length=20)),
                ('analysis_bank', models.CharField(max_length=20)),
                ('analysis_machine', models.CharField(max_length=20)),
                ('analysis_group', models.CharField(max_length=20)),
                ('finance_group', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
            options={
                'db_table': 'credits_analysis',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.Person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='api.Person')),
            ],
            options={
                'db_table': 'contacts_persons',
            },
        ),
    ]
